# Generated by Django 3.2.25 on 2024-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepictures/default.png', null=True, upload_to='profilepictures'),
        ),
    ]
