# Generated by Django 3.2.25 on 2024-11-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_wishlistitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
    ]
